<?php

    $title = "Cardapio da Dona Rita";
    $desenvolvedor = "Lucas da Silva Alves";

    $tutoriais = array(
        0 => array('id'=>'1', 
        'titulo'=>'DOMINGO DO CHURRASCO',
        'autor' => 'Lucas S. Alves', 
        'data' => '2022-08-10',
        'descricao'=>'É uma nova tendência que tem conquistado muito os nossos clientes. Afinal, é o prato mais consumido do país. Neste prato contém, Arroz Branco, Picanha Assada, Feijão Tropeiro, Vinagrete e Mandioca',
        'imagem'=>'img/img2.jpg'),
        1 => array('id'=>'2',
         'titulo'=>'SEGUNDA DA FEIJOADA', 
         'autor' => 'Lucas S. Alves', 
         'data' => '2022-08-10',
         'descricao'=>'Se tem um prato que está no coração do brasileiro, esse prato é a Feijoada. Acompanha: Arroz Branco, Farofa com Couve e Torresmo, Molho de Pimenta e nossa Famosa Salada Tropical',
         'imagem'=>'img/fejoada.png'),
        2 => array('id'=>'3',
        'titulo'=>'TERÇA DA CARNE AO MOLHO MADEIRA',
        'autor' => 'Lucas S. Alves', 
        'data' => '2022-08-10',
        'descricao'=>'Acompanhamento: Arroz Colorido, Purê de Batata, Farofa, Salada e um Delicioso Lagarto ao Molho Madeira.',
        'imagem'=>'img/molhomadeira.JPG'),
        3 => array('id'=>'4',
        'titulo'=>'QUARTA DA MARMITA FITNESS', 
        'autor' => 'Lucas S. Alves', 
        'data' => '2022-08-10',
        'descricao'=>'Está marmita é para aqueles que quer manter uma alimentação equilibrada. Pois conta com ingredientes saudável e bastante variado. Acompanha: Almôndegas de Frango Fit com Aveia, Cogumelos com Espinafre no Leite de Cocô, Peixe Grelhado e Couvê Refogada.',
        'imagem'=>'img/marmita-fitness.jpg'),
        4 => array('id'=>'5', 
        'titulo'=>'QUINTA DA ALMÔNDEGAS AO MOLHO SUGO',
        'autor' => 'Lucas S. Alves', 
        'data' => '2022-08-10',
        'descricao'=>'Acompanhamento: Arroz Branco, Feijão Carioca ao Caldo, Almôndegas ao Molho Sugo, Purê de Abóbora, Macarrão e Salada.',
        'imagem'=>'img/Almondegas-sugo.jpg'),
        5 => array('id'=>'6', 'titulo'=>
        'SEXTA DA PARMEGIANA DE FRANGO', 
        'autor' => 'Lucas S. Alves', 
        'data' => '2022-08-10',
        'descricao'=>'Acompanha: Arroz, Parmegiana de Frango, Batata Frita e Salada de Legumes',
        'imagem'=>'img/parmegiana-de-frango.jpg'),
        6 => array('id'=>'7', 
        'titulo'=>'SÁBADO DA ROCAMBOLE RECHEADO', 
        'autor' => 'Lucas S. Alves', 
        'data' => '2022-08-10',
        'descricao'=>'Neste famoso e disputado prato temos: Arroz, Brócolis, um delicioso Rocambole Recheado com Queijo e Bacon e Salada Italiana',
        'imagem'=>'img/rocambole.jpg'),
    );